version: 2.1
jobs: 
  build:
    docker:
      - image: cimg/node:17.2.0
      auth:
        username: coralsparrow
        password: $DOCKERHUB_PASS
    steps:
      - checkout
        run: echo "hello world"